// /frontend/src/env.ts
export const env = {
  VITE_KINDE_ISSUER_URL: import.meta.env.VITE_KINDE_ISSUER_URL!,
  VITE_KINDE_CLIENT_ID: import.meta.env.VITE_KINDE_CLIENT_ID!,
  VITE_KINDE_AUDIENCE: import.meta.env.VITE_KINDE_AUDIENCE!,
  VITE_KINDE_REDIRECT_URI: import.meta.env.VITE_KINDE_REDIRECT_URI!,
  VITE_KINDE_LOGOUT_REDIRECT_URI: import.meta.env.VITE_KINDE_LOGOUT_REDIRECT_URI!,
}